# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ripser_cpp <- function(input_points, dim, thresh, format) {
    .Call('_TDAstats_ripser_cpp', PACKAGE = 'TDAstats', input_points, dim, thresh, format)
}

