# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ripser_cpp <- function(input_points, dim, thresh, p, format) {
    .Call('_TDAstats_ripser_cpp', PACKAGE = 'TDAstats', input_points, dim, thresh, p, format)
}

test <- function() {
    invisible(.Call('_TDAstats_test', PACKAGE = 'TDAstats'))
}

